MENDER/STANDALONE_DAEMON_DATA_DIR                 ?= "/run/.mender-standalone-daemon/uploads"
MENDER/STANDALONE_DAEMON_BIST_DELAY_SECS          ?= "300"

MENDER/STANDALONE_DAEMON_ARTIFACT_PASSWD_DEFAULT   = "password"
MENDER/STANDALONE_DAEMON_ARTIFACT_PASSWD         ??= "${MENDER/STANDALONE_DAEMON_ARTIFACT_PASSWD_DEFAULT}"

MENDER/STANDALONE_DAEMON_ARTIFACT_ENCRYPT_EXT    ??= "AES256"
MENDER/STANDALONE_DAEMON_ARTIFACT_OPENSSL_OPTS   ??= "-aes-256-cbc -pbkdf2 -salt"
